# This work is released into the Public Domain under the
# terms of the Creative Commons CC0 1.0 Universal license.
# https://creativecommons.org/publicdomain/zero/1.0/

language: java

dist: xenial
before_install:
  - sudo apt-get install -y ant ant-contrib junit4

branches:
  only:
  - travis-ci

install:
  - cp -v .travis.ant.local ant.local
  - ls -lF /usr/share/java/
