name: Build Server Image

on: workflow_dispatch  # manually triggered

jobs:
  do_all_steps:
    runs-on: ubuntu-20.04
    steps:

    - name: Checkout Branch
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v1.4.2
      with:
        java-version: 11

    - name: Compile Java
      run: ant compile

    - name: Build Image
      run: make -C src/pod/ build

#@@@  push image
