name: Promote Server Image to IBM Cloud

on:
  workflow_dispatch:  # manually triggered
    inputs:
      image_tag:
        description: Tag of the image to promote, for example "main-8".
        default:     main-
        required:    true

jobs:
  promote:
    runs-on: ubuntu-20.04
    env:
      GHCR_IMAGE: docker://ghcr.io/rolandweber/pityoulish/server
      ICR_IMAGE:  docker://us.icr.io/pityoulish/server

    steps:

    - name: Login to IBM Cloud Container Registry
      run: skopeo login -u iamapikey -p "${{ secrets.IBM_CLOUD_API_KEY }}" \
                  us.icr.io

    - name: Promote image
      run: skopeo copy \
                  "$GHCR_IMAGE:${{ github.event.inputs.image_tag }}' \
                  "$ICR_IMAGE:${{ github.event.inputs.image_tag }}'

    - name: Retag image as latest
      run: skopeo copy \
                  "$ICR_IMAGE:${{ github.event.inputs.image_tag }}' \
                  "$ICR_IMAGE::latest"
